# Generated by Django 2.1.3 on 2018-11-11 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creativeRutApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participantname',
            old_name='question_text',
            new_name='Pname',
        ),
    ]
