# Generated by Django 2.1.3 on 2018-11-11 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creativeRutApp', '0002_auto_20181111_1229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participantname',
            old_name='Pname',
            new_name='ParticipantName',
        ),
    ]
